hw_12 first commit
ValentynaRudenko/Prjctr_Python_beginner pull request #5
Opened 2023-09-03 13:22 UTC by ValentynaRudenko

Hi!

Could you help me to resolve the issue?🙏

At the beginning of the file, you can see a commented part of the code - I created it due to an example on the site GIPHY. But it returned an Error `ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002`)
It left even after I updated it (`pip install –upgrade certifi`).

BUT
When I COPY-PASTE the example code - it works. I can't understand why.🤷‍♀️ 
Maybe you can suggest why it happened?

2023-09-03 20:57 UTC, bielanm requested changes

2023-09-03 20:57 UTC, bielanm commented on hw_12/task_1.py
> +MY_API_KEY = "lyX7TkrxLgHgtKG3wbku361Ndr96KIoS"
API ключі не повинні зʼявлятися в коді - їх потрібно задавати змінними оточення, або хоча б зчитуватися з файла. 
Ось можеш статтю продивитись там є приклади.

І тобі треба буде не новий кому зробити - а додати до попереднього, щоб цей ключ не зберігся в історії.
або git commit --amend, або git reset HEAD~1 і новий коміт

2023-09-04 10:31 UTC, bielanm commented on hw_12/task_1.py
> +MY_API_KEY = "lyX7TkrxLgHgtKG3wbku361Ndr96KIoS"
https://www.twilio.com/blog/environment-variables-python

2023-09-04 10:31 UTC, bielanm commented on hw_12/task_1.py
> +# python
повидахляй будь ласка, якщо не потрібно більше)

2023-09-04 10:32 UTC, bielanm commented on hw_12/task_1.py
> +# print(type(response_json["data"]))
і оце теж повидаляй)

2023-09-04 17:40 UTC, ValentynaRudenko commented on hw_12/task_1.py
> +MY_API_KEY = "lyX7TkrxLgHgtKG3wbku361Ndr96KIoS"
О, дякую!
Дуже корисна інформація!

Виправила та повидяляла зайве.
Зробила `git commit --amend`

2023-09-05 09:10 UTC, bielanm approved these changes

2023-09-08 08:18 UTC, merged