hw_13 tasks 1-3, first commit
ValentynaRudenko/Prjctr_Python_beginner pull request #6
Opened 2023-09-10 08:50 UTC by ValentynaRudenko

Міша, привіт!

Для з optional зробила лише 3-ю таску, але, чесно кажучі не до кінця зрозуміла як має бути правильно. Зробила 2 варіанти: task_3.1, task_3.2

2023-09-10 11:55 UTC, bielanm requested changes

2023-09-10 11:55 UTC, bielanm commented on hw_13/task_1.py
> +        print(func(*args, **kwargs))
Ти повторно викликаєш функцію func(), підозрюю що сталося це через те, що перший раз ти не побачила жодного результату (що логічно, бо в тебе декоратор не повертає значення, а повинен). Допиши return який повертає результат і прибери повторний виклик.

2023-09-10 11:55 UTC, bielanm commented on hw_13/task_3.1.py
> +        arg_status = [isinstance(arg, int) for arg in args]
загалом правильно, але в даному випадку твій декоратор працює тільки на перевірку функцій з int параметрами, а тобі треба написати в загальному вигляді. Для цього треба якось витягати типи параметрів з функції.
Використай: https://docs.python.org/3/library/inspect.html#inspect.signature
там є приклад як дістати параметер

2023-09-10 11:55 UTC, bielanm commented on hw_13/task_3.1.py
> +            func(*args, **kwargs)
знову забула про return results

2023-09-12 15:03 UTC, ValentynaRudenko commented on hw_13/task_3.1.py
> +            func(*args, **kwargs)
Міша, привіт!

Трохи переплутала гілки коли комітила зміни:
- `task 1 `- це виправлення в task_1
- `task 3.1` - це виправлення в task_3.1
- `hw_13 corrected` - це завдання з наступної домашки

2023-09-12 15:14 UTC, bielanm approved these changes

2023-09-12 15:14 UTC, bielanm commented on hw_14/task_3.py
> +        self.speed -= 5
`self.speed = max(self.speed - 5, 0)`

2023-09-12 15:26 UTC, merged