tasks 1,2
ValentynaRudenko/Prjctr_Python_beginner pull request #7
Opened 2023-09-28 05:35 UTC by ValentynaRudenko

2023-09-28 10:46 UTC, bielanm requested changes

2023-09-28 10:46 UTC, bielanm commented on hw_15/task_1.py
> +                instances.append(cls(name=row[0], author=row[1]))
А ти впевнена що це працює так, як ти того очікуєш?
 Бо row[0], row[1] в даному випадку повинні бути першою і другою літерою рядка.
 
Також воно повинно відпадати, бо `cls` в твоєму випадку буде посиланням на обʼєкт класу Book (щоб він був методом класу - треба зробити йому @classmethod). І навіть коли ти так зробиш - то конструктор класу Book приймає 4 аргумента, а в тебе лише 2 передається.

2023-09-28 10:46 UTC, bielanm commented on hw_15/task_2.py
> +                if d == dish:
Якщо я правильно зрозумів, то ти береш у дікта menu список ключів, і перевіряш чи сходиться він з dish. 
Загалом це приблизно відповідає операції `menu[dish]`:)

2023-09-28 18:16 UTC, ValentynaRudenko commented on hw_15/task_1.py
> +                instances.append(cls(name=row[0], author=row[1]))
Corrected code:

`def read(self):
        print(f"The book {self.name} by author {self.author}.\n"
              f"Price is ${self.price}")`

2023-10-03 21:52 UTC, bielanm approved these changes

2023-10-08 12:43 UTC, merged